csv_data <- read.csv("/Users/cooperowen/Downloads/sample_gfw.csv", stringsAsFactors = FALSE)
tsv_data <- read.csv("/Users/cooperowen/Downloads/sample_gfw.tsv", stringsAsFactors = FALSE)
txt_data <- read.csv("/Users/cooperowen/Downloads/sample_gfw.txt", stringsAsFactors = FALSE)
devtools::load_all()
csv_data_gfw <- read_gfw_data("test data/extdata/sample_gfw.csv")
tsv_data_gfw <- read_gfw_data("test data/extdata/sample_gfw.tsv")
txt_data_gfw <- read_gfw_data("test data/extdata/sample_gfw.txt")
nrow(csv_data_gfw) == nrow(tsv_data_gfw)
nrow(csv_data_gfw) == nrow(txt_data_gfw)
