#' Calculate Trip Temporal and Spatial Displacement Statistics
#'
#' Evaluates elapsed trip duration and calculates point-by-point distance from
#' a static breeding colony coordinate.
#'
#' @param tracks An `sf` tracking object. Must contain a valid `time` column
#'   in POSIXct format and a `trip_id` column.
#' @param colony_coords Numeric vector. A named vector containing `lon` and
#'   `lat`, specifying the breeding colony location.
#'
#' @return A modified version of the input `sf` object with three added columns:
#'   `duration_hrs`, `dist_to_colony_m`, and `max_dist_km`.
#'
#' @export
calculate_trip_stats <- function(tracks, colony_coords) {
  if (!inherits(tracks, "sf")) {
    stop("`tracks` must be an sf object.")
  }

  if (!all(c("time", "trip_id") %in% names(tracks))) {
    stop("`tracks` must contain `time` and `trip_id` columns.")
  }

  if (!is.numeric(colony_coords) ||
      !all(c("lon", "lat") %in% names(colony_coords))) {
    stop("`colony_coords` must be a named numeric vector with names `lon` and `lat`.")
  }

  tracks <- tracks %>%
    dplyr::group_by(trip_id) %>%
    dplyr::mutate(
      duration_hrs = as.numeric(
        difftime(
          max(time, na.rm = TRUE),
          min(time, na.rm = TRUE),
          units = "hours"
        )
      )
    ) %>%
    dplyr::ungroup()

  colony_sf <- sf::st_sfc(
    sf::st_point(c(colony_coords[["lon"]], colony_coords[["lat"]])),
    crs = sf::st_crs(tracks)
  )

  tracks$dist_to_colony_m <- as.numeric(sf::st_distance(tracks, colony_sf))

  tracks <- tracks %>%
    dplyr::group_by(trip_id) %>%
    dplyr::mutate(
      max_dist_km = max(dist_to_colony_m, na.rm = TRUE) / 1000
    ) %>%
    dplyr::ungroup()

  tracks
}


#' Calculate Spatial Polygon Surface Coverage Areas
#'
#' Evaluates geographic surface boundaries for calculated home range or core
#' utilization polygons and appends area values in square kilometers.
#'
#' @param sf_polys An `sf` spatial polygon layer containing home range boundary
#'   geometries.
#'
#' @return The original `sf` data frame with a numeric column named `area_km2`.
#'
#' @export
calculate_area_metrics <- function(sf_polys) {
  if (!inherits(sf_polys, "sf")) {
    stop("`sf_polys` must be an sf object.")
  }

  sf_polys$area_km2 <- as.numeric(sf::st_area(sf_polys)) / 1e6

  sf_polys
}


#' Extract Spatial Centroids from Area Features
#'
#' Computes geographic centroids for calculated boundary polygons or utilization
#' contours.
#'
#' @param sf_polys An `sf` spatial feature collection containing target polygons.
#'
#' @return An `sf` spatial point object representing feature centroids.
#'
#' @export
get_spatial_centroids <- function(sf_polys) {
  if (!inherits(sf_polys, "sf")) {
    stop("`sf_polys` must be an sf object.")
  }

  sf::st_centroid(sf_polys)
}


#' Export Space-Use Layers
#'
#' Exports an `sf` spatial object as a GeoPackage file.
#'
#' @param sf_obj An `sf` spatial object to export.
#' @param filename Character. Output filename without the `.gpkg` extension.
#'
#' @return Invisibly returns the path to the written GeoPackage file.
#'
#' @export
export_spaceuse_layers <- function(sf_obj, filename) {
  if (!inherits(sf_obj, "sf")) {
    stop("`sf_obj` must be an sf object.")
  }

  if (!is.character(filename) || length(filename) != 1) {
    stop("`filename` must be a single character string.")
  }

  out_path <- paste0(filename, ".gpkg")

  sf::st_write(
    sf_obj,
    dsn = out_path,
    append = FALSE,
    quiet = TRUE
  )

  invisible(out_path)
}


#' Plot Home Range and Core Space-Use Hotspots
#'
#' Generates a spatial map illustrating core home range boundaries and
#' utilization polygons.
#'
#' @param sf_polys An `sf` polygon dataset generated by `get_isopleths()`.
#' @param title Character. The map title. Default is
#'   `"Seabird Space-Use Hotspots"`.
#'
#' @return A `ggplot2` plot object.
#'
#' @export
plot_hotspot_map <- function(sf_polys, title = "Seabird Space-Use Hotspots") {
  if (!inherits(sf_polys, "sf")) {
    stop("Input `sf_polys` must be a valid sf spatial features collection.")
  }

  fill_col <- if ("id" %in% names(sf_polys)) {
    "id"
  } else {
    names(sf_polys)[1]
  }

  ggplot2::ggplot() +
    ggplot2::geom_sf(
      data = sf_polys,
      ggplot2::aes(fill = .data[[fill_col]]),
      alpha = 0.4,
      color = "black"
    ) +
    ggplot2::scale_fill_viridis_d(
      option = "viridis",
      name = "UD Threshold (%)"
    ) +
    ggplot2::labs(
      title = title,
      subtitle = "Computed Core Areas (50%) and Range Extents (95%)",
      x = "Longitude",
      y = "Latitude"
    ) +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", size = 14),
      legend.position = "right"
    )
}
